#!/bin/bash

echo "TMUX CHEAT SHEET"
echo "====================="
echo ""
echo "Session Management"
echo "-------------------"
echo "New session: tmux new-session -s <name>"
echo "Attach to session: tmux attach -t <name>"
echo "List sessions: tmux list-sessions"
echo "Kill session: tmux kill-session -t <name>"
echo "Rename session: Ctrl + b, then : rename-session <new-name>"
echo ""
echo "Window Management"
echo "------------------"
echo "New window: Ctrl + b, then c"
echo "Switch window: Ctrl + b, then n (next) or p (previous)"
echo "Select window by number: Ctrl + b, then <number>"
echo "Rename window: Ctrl + b, then ,"
echo "Close window: Ctrl + b, then &"
echo "List windows: Ctrl + b, then w"
echo ""
echo "Pane Management"
echo "----------------"
echo "Split horizontally: Ctrl + b, then \""
echo "Split vertically: Ctrl + b, then %"
echo "Switch pane: Ctrl + b, then arrow key (← ↑ → ↓)"
echo "Resize pane: Ctrl + b, then :resize-pane -D/-U/-L/-R"
echo "Close pane: Ctrl + b, then x"
echo "Toggle pane zoom: Ctrl + b, then z"
echo "Move pane to new window: Ctrl + b, then !"
echo ""
echo "Copy & Paste Mode"
echo "------------------"
echo "Enter copy mode: Ctrl + b, then ["
echo "Move cursor: Arrow keys"
echo "Start selection: Space"
echo "Copy selection: Enter"
echo "Paste: Ctrl + b, then ]"
echo ""
echo "Other Commands"
echo "--------------"
echo "Show command prompt: Ctrl + b, then :"
echo "List key bindings: Ctrl + b, then ?"
echo "Reload config: Ctrl + b, then :source-file ~/.tmux.conf"
echo "Show time: Ctrl + b, then t"
echo "Send text to tmux pane: Ctrl + b, then :send-keys '<text>'"
